config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  get 'dashboards/index'
  root 'dashboards#index'

  namespace :admins do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :countries, controller: '/countries'
    resources :lanes
    resources :rounds
  end

  resources :countries
  resources :users, only: :show do
    resources :rounds, except: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lane.rb
class Lane < ApplicationRecord

  belongs_to :user
  has_many :rounds, dependent: :restrict_with_error

  validates :name, :user_id, presence: true
end

app/controllers/admins/lanes_controller.rb
class Admins::LanesController < Admins::AdminsController
  before_action :set_lane, only: [:show, :edit, :update, :destroy]

  # GET /admins/lanes
  # GET /admins/lanes.json
  def index
    @lanes = Lane.all
  end

  # GET /admins/lanes/1
  # GET /admins/lanes/1.json
  def show
  end

  # GET /admins/lanes/new
  def new
    @lane = Lane.new
  end

  # GET /admins/lanes/1/edit
  def edit
  end

  # POST /admins/lanes
  # POST /admins/lanes.json
  def create
    @lane = Lane.new(lane_params)

    respond_to do |format|
      if @lane.save
        format.html { redirect_to admins_lane_path(@lane), notice: 'Lane was successfully created.' }
        format.json { render :show, status: :created, location: @lane }
      else
        format.html { render :new }
        format.json { render json: @lane.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/lanes/1
  # PATCH/PUT /admins/lanes/1.json
  def update
    respond_to do |format|
      if @lane.update(lane_params)
        format.html { redirect_to @lane, notice: 'Lane was successfully updated.' }
        format.json { render :show, status: :ok, location: @lane }
      else
        format.html { render :edit }
        format.json { render json: @lane.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/lanes/1
  # DELETE /admins/lanes/1.json
  def destroy
    @lane.destroy
    respond_to do |format|
      format.html { redirect_to admins_lanes_url, notice: 'Lane was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lane
      @lane = Lane.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lane_params
      params.require(:lane).permit(:name, :description, :user_id)
    end
end

app/views/admins/lanes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admins, @lane]) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :description
    = f.input :user_id, collection: User.all, label_method: :name, value_method: :id, input_html: { class: 'selectpicker' }

  .form-actions
    = f.button :submit

app/views/admins/lanes/edit.html.haml
%h1
.row
  .col-md-12
    .card
      .card-header
        %h4.card-title Editing lane
      .card-body
        = render 'form'

        = link_to 'Show', admins_lane_path(@lane)
        \|
        = link_to 'Back', admins_lanes_path

app/views/admins/lanes/index.html.haml
.row
  .col-lg-12
    .card
      .card-header
        %h4.card-title Listing Lanes
        %p.card-category Setup countries matching
      .card-body
        = link_to 'New Lane', new_admins_lane_path
        %table.table.table-striped.datatable
          %thead
            %tr
              %th Name
              %th Description
              %th User
              %th
              %th
              %th

          %tbody
            - @lanes.each do |lane|
              %tr
                %td= lane.name
                %td= lane.description
                %td= lane.user.name
                %td= link_to 'Show', admins_lane_path(lane)
                %td= link_to 'Edit', edit_admins_lane_path(lane)
                %td= link_to 'Destroy', admins_lane_path(lane), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/lanes/new.html.haml
.row
  .col-md-12
    .card
      .card-header
        %h4.card-title create new lane
      .card-body
        = render 'form'

        = link_to 'Back', admins_lanes_path

app/views/admins/lanes/show.html.haml
.row
  .col-lg-12
    .card
      .card-header
        %h4.card-title Lane detail
        %p.card-category Lane has many rounds and each round has two sets.
      .card-body

        %p
          %b Name:
          = @lane.name
        %p
          %b Description:
          = @lane.description
        %p
          %b User manage the scoreboard:
          = @lane.user.name

        = link_to 'Edit', edit_admins_lane_path(@lane)
        \|
        = link_to 'Back', admins_lanes_path