config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  get 'dashboards/index'
  root 'dashboards#index'

  namespace :admins do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :countries, controller: '/countries'
    resources :lanes
    resources :rounds
  end

  resources :countries
  resources :users, only: :show do
    resources :rounds, except: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :trackable,  :confirmable, :lockable,
         :recoverable, :rememberable, :validatable

  has_one :lan

  validates :name, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

end

app/controllers/admins/users_controller.rb
class Admins::UsersController < Admins::AdminsController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /admins/users
  # GET /admins/users.json
  def index
    @users = User.all
  end

  # GET /admins/users/1
  # GET /admins/users/1.json
  def show
  end

  # GET /admins/users/new
  def new
    @user = User.new
  end

  # GET /admins/users/1/edit
  def edit
  end

  # POST /admins/users
  # POST /admins/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to admins_user_path(@user), notice: 'User was successfully created.' }
        format.json { render :show, status: :created }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/users/1
  # PATCH/PUT /admins/users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to admins_user_path(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/users/1
  # DELETE /admins/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admins_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :phone_number, :password, :password_confirmation)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  include Accessible
  skip_before_action :check_user, only: :destroy

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/views/admins/users/_form.html.haml
= simple_form_for [:admins, @user], wrapper: :horizontal_form,  html: { novalidate: false, class: 'form-horizontal needs-validation form-group' } do |f|
  .row
    .col-xs-12.col-md-6
      = f.input :name
      = f.input :email
      = f.input :password, hint: (t('devise.shared.minimum_password_length', count: @minimum_password_length) if @minimum_password_length), input_html: { autocomplete: "new-password", class: 'form-control' }
      = f.input :password_confirmation
      = f.input :phone_number
  .hr-line-dashed
  .form-group.row
    .col-sm-4.col-sm-offset-2.text-right
      %button.btn.btn-fill{:type => "submit"} Cancel
      = f.button :submit, class: 'btn btn-fill btn-primary'

app/views/admins/users/edit.html.haml
.row
  .col-md-12
    .card
      .card-header
        %h4.card-title Editing user
      .card-body
        = render 'form'

        = link_to 'Show', admins_user_path(@user)
        \|
        = link_to 'Back', admins_users_path

app/views/admins/users/index.html.haml
.row
  .col-md-12
    .card
      .card-header
        %h4.card-title Listing users
      .card-body
        %table.table.table-striped.datatable
          %thead
            %tr
              %th Name
              %th Email
              %th Phone
              %th
              %th
              %th

          %tbody
            - @users.each do |user|
              %tr
                %td= user.name
                %td= user.email
                %td= user.phone_number
                %td= link_to 'Show', admins_user_path(user)
                %td= link_to 'Edit', edit_admins_user_path(user)
                %td= link_to 'Destroy', admins_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }

        %br

        = link_to 'New User', new_admins_user_path

app/views/admins/users/new.html.haml
.row
  .col-md-12
    .card
      .card-header
        %h4.card-title New user
      .card-body
        = render 'form'

app/views/admins/users/show.html.haml
.row
  .col-md-8
    .card
      .card-header
        %h5.title Edit Profile
      .card-body
        %p
          %b Name:
          = @user.name
        %p
          %b Email:
          = @user.email
        %p
          %b Phone:
          = @user.phone_number

        = link_to 'Edit', edit_admins_user_path(@user)
        \|
        = link_to 'Back', admins_users_path

        = simple_form_for [:admins, @user],  html: { novalidate: false, class: 'form-horizontal needs-validation form-group' } do |f|
          .row
            .col-xs-12.col-md-6
              = f.input :name
              = f.input :email
              = f.input :password, hint: (t('devise.shared.minimum_password_length', count: @minimum_password_length) if @minimum_password_length), input_html: { autocomplete: "new-password", class: 'form-control' }
              = f.input :password_confirmation
              = f.input :phone_number
              = f.button :submit, class: 'btn btn-fill btn-primary pull-right'
  .col-md-4
    .card.card-user
      .card-body
        %p.card-text
        .author
          .block.block-one
          .block.block-two
          .block.block-three
          .block.block-four
          %a{:href => "javascript:void(0)"}
            = image_pack_tag "emilyz.jpg", class: 'avatar'
            %h5.title Mike Andrew
          %p.description
            Ceo/Co-Founder
        .card-description
          Do not be scared of the truth because we need to restart the human foundation in truth And I love you like Kanye loves Kanye I love Rick Owens’ bed design but the back is...
      .card-footer
        .button-container
          %button.btn.btn-icon.btn-round.btn-facebook{:href => "javascript:void(0)"}
            %i.fab.fa-facebook
          %button.btn.btn-icon.btn-round.btn-twitter{:href => "javascript:void(0)"}
            %i.fab.fa-twitter
          %button.btn.btn-icon.btn-round.btn-google{:href => "javascript:void(0)"}
            %i.fab.fa-google-plus