config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  get 'dashboards/index'
  root 'dashboards#index'

  namespace :admins do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :countries, controller: '/countries'
    resources :lanes
    resources :rounds
  end

  resources :countries
  resources :users, only: :show do
    resources :rounds, except: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.haml
%footer.footer
  .container-fluid
    %ul.nav
      %li.nav-item
        %a.nav-link{:href => "javascript:void(0)"}
          Creative Tim
      %li.nav-item
        %a.nav-link{:href => "javascript:void(0)"}
          About Us
      %li.nav-item
        %a.nav-link{:href => "javascript:void(0)"}
          Blog
    .copyright
      ©
      %span#footer-year
      made with
      %i.tim-icons.icon-heart-2
      by
      %a{:href => "javascript:void(0)", :target => "_blank"} Webuilder Team
      for a better web.

app/views/layouts/_left_sidebar.haml
.sidebar-wrapper
  .logo
    %a.simple-text.logo-mini{:href => "javascript:void(0)"}
      CP
    %a.simple-text.logo-normal{:href => "javascript:void(0)"}
      Cambodia Petanque
  %ul.nav
    - if current_admin
      %li{ class: "#{is_active_controller('dashboards')}" }
        = link_to admins_dashboard_path do
          %i.tim-icons.icon-chart-pie-36
          %p Dashboard
      %li{ :class => "#{is_active_controller('users')}" }
        = link_to admins_users_path do
          %i.tim-icons.icon-single-02
          %p Users
      %li{ :class => "#{is_active_controller('countries')}" }
        = link_to admins_countries_path do
          %i.tim-icons.icon-world
          %p Countries
      %li
        %a{"aria-expanded" => "false", "data-toggle" => "collapse", :href => "#matchingSetting"}
          %i.tim-icons.icon-settings
          %p
            Matches
            %b.caret
        #matchingSetting.collapse
          %ul.nav
            %li
              = link_to admins_lanes_path, class: "#{is_active_controller('lanes')}" do
                %span.sidebar-mini-icon L
                %span.sidebar-normal Lanes
            %li
              = link_to admins_rounds_path, class: "#{is_active_controller('rounds')}" do
                %span.sidebar-mini-icon R
                %span.sidebar-normal Rounds
            %li
              %a{:href => ""}
                %span.sidebar-mini-icon T
                %span.sidebar-normal Timeline
            %li
              %a{:href => ""}
                %span.sidebar-mini-icon L
                %span.sidebar-normal Login
            %li
              %a{:href => ""}
                %span.sidebar-mini-icon R
                %span.sidebar-normal Register
            %li
              %a{:href => ""}
                %span.sidebar-mini-icon LS
                %span.sidebar-normal Lock Screen
            %li
              %a{:href => ""}
                %span.sidebar-mini-icon UP
                %span.sidebar-normal User Profile
    - elsif current_user
      %li
        = link_to user_rounds_path(current_user), class: "#{is_active_controller('rounds')}" do
          %i.tim-icons.icon-world
          %p Rounds
    %li
      %a{"data-toggle" => "collapse", :href => "#mapsExamples"}
        %i.tim-icons.icon-pin
        %p
          Maps
          %b.caret
      #mapsExamples.collapse
        %ul.nav
          %li
            %a{:href => ""}
              %span.sidebar-mini-icon GM
              %span.sidebar-normal Google Maps
          %li
            %a{:href => ""}
              %span.sidebar-mini-icon FM
              %span.sidebar-normal Full Screen Map
          %li
            %a{:href => ""}
              %span.sidebar-mini-icon VM
              %span.sidebar-normal Vector Map

    %li
      %a{:href => ""}
        %i.tim-icons.icon-chart-bar-32
        %p Charts
    %li
      %a{:href => ""}
        %i.tim-icons.icon-time-alarm
        %p Calendar

app/views/layouts/_main_navbar.haml
.navbar-minimize-fixed
  %button.minimize-sidebar.btn.btn-link.btn-just-icon
    %i.tim-icons.icon-align-center.visible-on-sidebar-regular.text-muted
    %i.tim-icons.icon-bullet-list-67.visible-on-sidebar-mini.text-muted

app/views/layouts/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-absolute.navbar-transparent
  .container-fluid
    .navbar-wrapper
      .navbar-minimize.d-inline
        %button.minimize-sidebar.btn.btn-link.btn-just-icon{"data-original-title" => "Sidebar toggle", "data-placement" => "right", :rel => "tooltip"}
          %i.tim-icons.icon-align-center.visible-on-sidebar-regular
          %i.tim-icons.icon-bullet-list-67.visible-on-sidebar-mini
      .navbar-toggle.d-inline
        %button.navbar-toggler{:type => "button"}
          %span.navbar-toggler-bar.bar1
          %span.navbar-toggler-bar.bar2
          %span.navbar-toggler-bar.bar3
      %a.navbar-brand{:href => "javascript:void(0)"} Dashboard
    %button.navbar-toggler{"aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navigation", "data-toggle" => "collapse", :type => "button" }
      %span.navbar-toggler-bar.navbar-kebab
      %span.navbar-toggler-bar.navbar-kebab
      %span.navbar-toggler-bar.navbar-kebab
    #navigation.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        %li.search-bar.input-group
          %button#search-button.btn.btn-link{"data-target" => "#searchModal", "data-toggle" => "modal"}
            %i.tim-icons.icon-zoom-split
            %span.d-lg-none.d-md-block Search
        %li.dropdown.nav-item
          %a.dropdown-toggle.nav-link{"data-toggle" => "dropdown", :href => "javascript:void(0)"}
            .notification.d-none.d-lg-block.d-xl-block
            %i.tim-icons.icon-sound-wave
            %p.d-lg-none
              Notifications
          %ul.dropdown-menu.dropdown-menu-right.dropdown-navbar
            %li.nav-link
              %a.nav-item.dropdown-item{:href => "#"} Mike John responded to your email
            %li.nav-link
              %a.nav-item.dropdown-item{:href => "javascript:void(0)"} You have 5 more tasks
            %li.nav-link
              %a.nav-item.dropdown-item{:href => "javascript:void(0)"} Your friend Michael is in town
            %li.nav-link
              %a.nav-item.dropdown-item{:href => "javascript:void(0)"} Another notification
            %li.nav-link
              %a.nav-item.dropdown-item{:href => "javascript:void(0)"} Another one
        %li.dropdown.nav-item
          %a.dropdown-toggle.nav-link{"data-toggle" => "dropdown", :href => "#"}
            .photo
              = image_pack_tag "mike.jpg"
            %b.caret.d-none.d-lg-block.d-xl-block
            %p.d-lg-none
              Log out
          %ul.dropdown-menu.dropdown-navbar


            %li.nav-link
              %a.nav-item.dropdown-item{:href => "javascript:void(0)"} Profile
            %li.nav-link
              %a.nav-item.dropdown-item{:href => "javascript:void(0)"} Settings
            %li.dropdown-divider
            - if admin_signed_in?
              %li.nav-link
                = link_to'Log out', destroy_admin_session_path, method: :delete, class: 'nav-item dropdown-item'
            - elsif user_signed_in?
              %li.nav-link
                = link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-item dropdown-item'
            - else
              %li.nav-link
                = link_to 'Login', new_user_session_path, class: 'nav-item dropdown-item'
        %li.separator.d-lg-none

#searchModal.modal.modal-search.fade{"aria-hidden" => "true", "aria-labelledby" => "searchModal", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %input#inlineFormInputGroup.form-control{:placeholder => "SEARCH", :type => "text"}/
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %i.tim-icons.icon-simple-remove

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = action_cable_meta_tag
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/

    %title PtcScoreboard
    = csrf_meta_tags
    = csp_meta_tag

    / Fonts and icons
    %link{:href => "https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800", :rel => "stylesheet"}/

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body{ 'data-gr-c-s-loaded': true, id: "#{controller_name}-#{action_name}" }
    .wrapper{ data: { notice: notice, alert: alert } }
      / Main navbar
      = render 'layouts/main_navbar'
      .sidebar{ data: '' }
        / Main sidebar
        = render 'layouts/left_sidebar'
      / Main Panel
      .main-panel{ data: '' }
        / Nav bar
        = render 'layouts/navbar'
        / Content area
        .content
          = yield
        = render 'layouts/footer'

= javascript_pack_tag controller_name, 'data-turbolinks-track': 'reload'

app/views/layouts/login.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/

    %title PtcScoreboard
    = csrf_meta_tags
    = csp_meta_tag

    / Fonts and icons
    %link{:href => "https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800", :rel => "stylesheet"}/

    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'

  %body.login-page
    / Navbar
    %nav.navbar.navbar-expand-lg.navbar-absolute.navbar-transparent.fixed-top
      .container-fluid
        .navbar-wrapper
          .navbar-toggle.d-inline
            %button.navbar-toggler{:type => "button"}
              %span.navbar-toggler-bar.bar1
              %span.navbar-toggler-bar.bar2
              %span.navbar-toggler-bar.bar3
          %a.navbar-brand{:href => "javascript:void(0)"} Login Page
        %button.navbar-toggler{"aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navigation", "data-toggle" => "collapse", :type => "button"}
          %span.navbar-toggler-bar.navbar-kebab
          %span.navbar-toggler-bar.navbar-kebab
          %span.navbar-toggler-bar.navbar-kebab
        #navigation.collapse.navbar-collapse
          %ul.navbar-nav.ml-auto
            %li.nav-item
              %a.nav-link.text-primary{:href => "#{root_path}"}
                %i.tim-icons.icon-minimal-left
                Back to Dashboard
            %li.nav-item
              = link_to new_user_session_path, class: 'nav-link' do
                %i.tim-icons.icon-single-02
                Login
            %li.nav-item
              %a.nav-link{:href => "lock.html"}
                %i.tim-icons.icon-lock-circle
                Lock
    #searchModal.modal.modal-search.fade{"aria-hidden" => "true", "aria-labelledby" => "searchModal", :role => "dialog", :tabindex => "-1"}
      .modal-dialog{:role => "document"}
        .modal-content
          .modal-header
            %input#inlineFormInputGroup.form-control{:placeholder => "SEARCH", :type => "text"}/
            %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
              %i.tim-icons.icon-simple-remove
    / End Navbar
    .wrapper.wrapper-full-page{ data: { notice: notice, alert: alert } }
      .full-page.login-page
        / you can change the color of the filter page using: data-color="blue | purple | green | orange | red | rose "
        .content
          .container
            .col-lg-4.col-md-6.ml-auto.mr-auto
              = yield
        %footer.footer
          .container-fluid
            %ul.nav
              %li.nav-item
                %a.nav-link{:href => "javascript:void(0)"}
                  Creative Tim
              %li.nav-item
                %a.nav-link{:href => "javascript:void(0)"}
                  About Us
              %li.nav-item
                %a.nav-link{:href => "javascript:void(0)"}
                  Blog
            .copyright
              ©
              :javascript
                document.write(new Date().getFullYear())
              made with
              %i.tim-icons.icon-heart-2
              by
              %a{:href => "javascript:void(0)", :target => "_blank"} Creative Tim
              for a better web.
    }